# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Continuous < Formula
  desc "Continuous Simulation API: Build Simulators from OpenAPI or WSDL documents, create Simulations from them, and build Worlds that run Simulations together. Authenticate every request with an API key sent as a Bearer token."
  homepage "https://github.com/continuous-labs-ai/cli"
  version "0.1.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/continuous-labs-ai/cli/releases/download/v0.1.19/continuous_Darwin_x86_64.tar.gz"
      sha256 "7065d201f87a9282c894fc961e905337454b9ed11103f339f59e03e8019f8576"

      define_method(:install) do
        bin.install "continuous"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/continuous-labs-ai/cli/releases/download/v0.1.19/continuous_Darwin_arm64.tar.gz"
      sha256 "4b1ebe5fd9fbb0af9f330cb68bd73ece5d6b684d6ad2e8756b19040f424a9952"

      define_method(:install) do
        bin.install "continuous"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/continuous-labs-ai/cli/releases/download/v0.1.19/continuous_Linux_x86_64.tar.gz"
      sha256 "6f65fdc755d141428d1e954bc7d030f563693e9a779732a0c52582a6845b4538"
      define_method(:install) do
        bin.install "continuous"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/continuous-labs-ai/cli/releases/download/v0.1.19/continuous_Linux_arm64.tar.gz"
      sha256 "2b42c76fec526ddc6477602a5d93577cfbcc9f0aeb3ca4881241ab7d82f98331"
      define_method(:install) do
        bin.install "continuous"
      end
    end
  end
end
